import { Brain, Sparkles, Zap } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'

export function AIInsights() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="h-10 w-10 rounded-xl bg-indigo-100 flex items-center justify-center">
          <Brain className="h-5 w-5 text-indigo-600" />
        </div>
        <div>
          <h2 className="text-lg font-bold text-slate-800">AI Insights</h2>
          <p className="text-sm text-slate-500">LLM-powered risk narrative — coming in Phase 9</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {[
          {
            icon: Sparkles,
            title: 'Executive Narrative',
            desc: 'Natural-language summary of current risk posture, key drivers, and recommended focus areas, generated by an LLM from structured signals.',
            color: 'bg-violet-50 border-violet-200 text-violet-700',
          },
          {
            icon: Zap,
            title: 'Anomaly Explanations',
            desc: 'When statistical anomalies are detected, the LLM will provide context-aware explanations referencing historical patterns and seasonal norms.',
            color: 'bg-amber-50 border-amber-200 text-amber-700',
          },
          {
            icon: Brain,
            title: 'Recommendation Narratives',
            desc: 'Each rule-based recommendation will be augmented with LLM-generated rationale, drawing on incident history and best practice.',
            color: 'bg-blue-50 border-blue-200 text-blue-700',
          },
          {
            icon: Sparkles,
            title: 'Cross-Site Intelligence',
            desc: 'Pattern recognition across all sites to surface systemic risks that individual-site analysis may miss.',
            color: 'bg-green-50 border-green-200 text-green-700',
          },
        ].map(({ icon: Icon, title, desc, color }, i) => (
          <Card key={i} className={`border ${color.split(' ')[1]}`}>
            <CardContent className="py-5 flex gap-3">
              <div
                className={`h-9 w-9 rounded-lg flex items-center justify-center shrink-0 ${color.split(' ')[0]}`}
              >
                <Icon className={`h-4.5 w-4.5 ${color.split(' ')[2]}`} />
              </div>
              <div>
                <p className="text-sm font-semibold text-slate-800">{title}</p>
                <p className="text-sm text-slate-500 mt-1">{desc}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
